/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e48663d4-e2ef-4fef-8a00-5d505a138d6b",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "3270ae1153944a5fabc5a605dd21be9a",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
